optimizer_config:
    eps: 1e-08
    weight_decay: 1e-02
    betas: [0.9, 0.99]

scheduler_config:
    max_lr: 5e-05
    div_factor: 10
    final_div_factor: 1000
    total_steps: 4000
    anneal_strategy: cos

model: distilbert-base-uncased
batch_size: 32
dropout_rate: 0

val_check_interval: 500
accumulate_grad_batches: 1
