optimizer_config:
    eps: 1e-08
    weight_decay: 1e-01

scheduler_config:
    max_lr: 3e-05
    div_factor: 10
    final_div_factor: 1000
    total_steps: 200000
    anneal_strategy: cos

model: distilbert-base-uncased
batch_size: 32
dropout_rate: 0

val_check_interval: 10000
accumulate_grad_batches: 1
